'use client';

import { useState } from 'react';
import { ExampleStatement } from '@/lib/types';

interface Props {
  examples: ExampleStatement[];
}

const labelColor = (label: string) => {
  switch (label) {
    case 'Very Hawkish': return '#ef4444';
    case 'Hawkish':      return '#f97316';
    case 'Neutral':      return '#f59e0b';
    case 'Mildly Dovish':return '#34d399';
    case 'Dovish':       return '#22c55e';
    case 'Very Dovish':  return '#10b981';
    default:             return '#94a3b8';
  }
};

export default function StatementDemo({ examples }: Props) {
  const [selected, setSelected] = useState<ExampleStatement>(examples[0]);

  const pct = Math.round(selected.score * 100);
  const color = labelColor(selected.label);

  return (
    <div className="rounded-xl border border-[#1e2d50] bg-[#0f1629] p-6">
      <p className="text-xs font-semibold tracking-widest text-[#64748b] uppercase mb-1">
        Live Demo
      </p>
      <p className="text-white font-semibold mb-6">Statement Scorer</p>

      <p className="text-xs text-[#64748b] mb-2">Select an FOMC statement excerpt:</p>
      <select
        className="w-full rounded-lg border border-[#1e2d50] bg-[#162040] text-[#e2e8f0] text-sm
                   px-3 py-2.5 mb-6 focus:outline-none focus:border-[#3b82f6] cursor-pointer"
        onChange={e => setSelected(examples[parseInt(e.target.value)])}
      >
        {examples.map((ex, i) => (
          <option key={i} value={i}>{ex.label} — {ex.text.slice(0, 60)}…</option>
        ))}
      </select>

      <div className="rounded-lg bg-[#162040] border border-[#1e2d50] p-4 mb-6">
        <p className="text-sm text-[#e2e8f0] leading-relaxed italic">
          &ldquo;{selected.text}&rdquo;
        </p>
      </div>

      <div className="flex items-center justify-between mb-2">
        <p className="text-xs text-[#64748b]">Hawkishness Score</p>
        <span
          className="text-xs font-semibold px-2 py-0.5 rounded-full"
          style={{ background: `${color}22`, color }}
        >
          {selected.label}
        </span>
      </div>

      <div className="h-3 rounded-full bg-[#162040] overflow-hidden mb-2">
        <div
          className="h-full rounded-full transition-all duration-500"
          style={{
            width: `${pct}%`,
            background: `linear-gradient(to right, #22c55e, #f59e0b, #ef4444)`,
          }}
        />
      </div>

      <div className="flex justify-between text-xs text-[#64748b] mb-4">
        <span>Dovish (0.0)</span>
        <span className="font-mono font-semibold" style={{ color }}>
          {selected.score.toFixed(2)}
        </span>
        <span>Hawkish (1.0)</span>
      </div>

      <p className="text-xs text-[#475569]">
        Scores generated by a DistilBERT model fine-tuned on 88 labeled FOMC sentences.
      </p>
    </div>
  );
}
